export const AUTH = 'AUTH';

export const CREATE_JOB_BY_USER_ID = 'CREATE_JOB_BY_USER_ID';
export const UPDATE_JOB_BY_USER_ID = 'UPDATE_JOB_BY_USER_ID';
export const GET_JOBS = 'GET_JOBS';
export const ACCEPT_JOB_PROPOSAL = 'ACCEPT_JOB_PROPOSAL';

export const CREATE_JOB_PROPOSAL = 'CREATE_JOB_PROPOSAL';
export const GET_PROPOSALS = 'GET_PROPOSALS';

export const RESET_STORE = 'RESET_STORE';